---
ID: "1dcb2de2-e4cb-5ae4-89cd-411872f5af25"
Parent: "aaedc498-60e5-586f-a89b-31786e83b6c9"
Template: "aaedc498-60e5-586f-a89b-31786e83b6c9"
Path: "/sitecore/templates/Project/Styleguide/Styleguide-Layout-Tabs-Tab/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230228T211942Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb90aad1-3fe7-486d-8344-970a69a59104"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230228T211942Z
